;;; -*- Mode: LISP; package:maxima; syntax:common-lisp; -*- 
(in-package :maxima)
(DSKSETQ $N '3.) 
(ADD2LNC '$N $VALUES) 
(RESTORE-FACTS '((($KIND) $N $INTEGER) ((MGEQP) $N 0.))) 
(ADD2LNC '$N $PROPS) 
(DSKSETQ $P '3.) 
(ADD2LNC '$P $VALUES) 
(RESTORE-FACTS '((($KIND) $P $INTEGER) ((MGEQP) $P 0.))) 
(ADD2LNC '$P $PROPS) 
(DSKSETQ $Q '3.) 
(ADD2LNC '$Q $VALUES) 
(RESTORE-FACTS '((($KIND) $Q $INTEGER) ((MGEQP) $Q 0.))) 
(ADD2LNC '$Q $PROPS) 
(DEFPARAMETER AAAAA (GENSYM)) 
(REMCOMPARY '|$projERP|) 
(MREMPROP '|$projERP| 'ARRAY) 
(MPUTPROP '|$projERP| AAAAA 'HASHAR) 
(*ARRAY AAAAA 'T 131.) 
(FILLARRAY AAAAA
           '(128. 96. 5.
             (((3. |$te| 1. 3. 1.) . 0.) ((3. |$tm| 2. 3. 3.) . 0.)) NIL
             (((3. |$tm| 3. 3. 0.) (MTIMES SIMP) -2. ((MEXPT SIMP) $A -2.)
               ((MEXPT SIMP) $B -2.) ((MEXPT SIMP) $C -1.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.))
                  ((MTIMES SIMP) ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $B 2.)))
                 $C $Ε
                 ((MEXPT SIMP)
                  ((%COS SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                    ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                      ((MEXPT SIMP RATSIMP) $B 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  3.))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.))
                  ((MTIMES SIMP) ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $B 2.)))
                 $C $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%SIN SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                    ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                      ((MEXPT SIMP RATSIMP) $B 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.)))))
             (((3. |$te| 3. 1. 2.) . 0.)) NIL NIL NIL
             (((3. |$te| 2. 3. 1.) . 0.) ((3. |$tm| 3. 3. 3.) . 0.))
             (((3. |$tm| 0. 0. 2.) . 0.)) NIL NIL (((3. |$tm| 0. 1. 0.) . 0.))
             NIL NIL (((3. |$te| 3. 3. 1.) . 0.))
             (((3. |$te| 0. 0. 0.) . 0.) ((3. |$tm| 1. 0. 2.) . 0.))
             (((3. |$tm| 0. 1. 3.) . 0.)) NIL
             (((3. |$tm| 1. 1. 0.) (MTIMES SIMP) -4. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -1.)
               ((MEXPT SIMP)
                ((MPLUS SIMP)
                 ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $A 3.) $B)
                 ((MTIMES SIMP) 4. $A ((MEXPT SIMP RATSIMP) $B 3.)))
                -1.)
               ((MEXPT SIMP) $C -4.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -30. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.))
                  ((MTIMES SIMP) -60. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 2.))
                  ((MTIMES SIMP) -30. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $B 4.)))
                 ((MEXPT SIMP RATSIMP) $C 4.) $Ε
                 ((MEXPT SIMP)
                  ((%COS SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                    ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                      ((MEXPT SIMP RATSIMP) $B 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  3.))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 42. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.))
                  ((MTIMES SIMP) 132. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 2.))
                  ((MTIMES SIMP) 42. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $B 4.)))
                 ((MEXPT SIMP RATSIMP) $C 4.) $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%SIN SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                    ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                      ((MEXPT SIMP RATSIMP) $B 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 24. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) 24. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 6.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) 37. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) 25. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 4.))
                    ((MTIMES SIMP) -12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $B 6.)))
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -2. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.))
                    ((MTIMES SIMP) -9. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) -7. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%COS SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.))
                ((MTIMES SIMP)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -82. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 3.) ((MEXPT SIMP RATSIMP) $B 2.)
                   $C)
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -30. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 3.))
                    ((MTIMES SIMP) 12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                     ((MEXPT SIMP RATSIMP) $B 2.)))
                   ((MEXPT SIMP RATSIMP) $C 3.)))
                 $Ε
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -24. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) -24. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 6.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -44. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) -44. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -20. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.))
                    ((MTIMES SIMP) -20. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.)))
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%SIN SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.)))))
             NIL (((3. |$te| 0. 0. 3.) . 0.)) NIL
             (((3. |$te| 1. 0. 0.) . 0.) ((3. |$tm| 2. 0. 2.) . 0.))
             (((3. |$te| 0. 1. 1.) . 0.) ((3. |$tm| 1. 1. 3.) . 0.)) NIL
             (((3. |$tm| 2. 1. 0.) . 0.)) NIL
             (((3. |$tm| 0. 3. 2.) . 0.) ((3. |$te| 1. 0. 3.) . 0.)) NIL
             (((3. |$te| 2. 0. 0.) . 0.) ((3. |$tm| 3. 0. 2.) . 0.))
             (((3. |$te| 1. 1. 1.) . 0.) ((3. |$tm| 2. 1. 3.) . 0.)) NIL
             (((3. |$tm| 3. 1. 0.) (MTIMES SIMP) 4. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -1.)
               ((MEXPT SIMP)
                ((MPLUS SIMP)
                 ((MTIMES SIMP) 2. ((MEXPT SIMP RATSIMP) $A 3.) $B)
                 ((MTIMES SIMP) 2. $A ((MEXPT SIMP RATSIMP) $B 3.)))
                -1.)
               ((MEXPT SIMP) $C -1.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -5. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.))
                  ((MTIMES SIMP) -2. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 2.))
                  ((MTIMES SIMP) 3. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $B 4.)))
                 $C $Ε
                 ((MEXPT SIMP)
                  ((%COS SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                    ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                      ((MEXPT SIMP RATSIMP) $B 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  3.))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 7. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.))
                  ((MTIMES SIMP) -2. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 2.))
                  ((MTIMES SIMP) 3. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $B 4.)))
                 $C $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%SIN SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                    ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                      ((MEXPT SIMP RATSIMP) $B 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.)))))
             NIL
             (((3. |$te| 0. 3. 0.) . 0.)
              ((3. |$tm| 1. 3. 2.) (MTIMES SIMP) 8. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -1.)
               ((MEXPT SIMP)
                ((MPLUS SIMP)
                 ((MTIMES SIMP) 8. ((MEXPT SIMP RATSIMP) $A 3.) $B)
                 ((MTIMES SIMP) 8. $A ((MEXPT SIMP RATSIMP) $B 3.)))
                -1.)
               ((MEXPT SIMP) $C -4.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -8. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) -8. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 6.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -5. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) -9. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 4.))
                    ((MTIMES SIMP) -4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $B 6.)))
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) 10. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.))
                    ((MTIMES SIMP) 3. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) -7. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%COS SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.))
                ((MTIMES SIMP) 14. ((MEXPT SIMP RATSIMP) $%PI 2.)
                 ((MEXPT SIMP RATSIMP) |$f_0| 3.) ((MEXPT SIMP RATSIMP) $A 3.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MEXPT SIMP RATSIMP) $C 3.) $Ε
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -8. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) -8. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 6.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) -12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.))
                    ((MTIMES SIMP) -4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.)))
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%SIN SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.))))
              ((3. |$te| 2. 0. 3.) . 0.))
             NIL (((3. |$te| 3. 0. 0.) . 0.))
             (((3. |$te| 2. 1. 1.) . 0.) ((3. |$tm| 3. 1. 3.) . 0.)) NIL
             (((3. |$te| 0. 3. 3.) . 0.)) NIL
             (((3. |$te| 1. 3. 0.) . 0.) ((3. |$tm| 2. 3. 2.) . 0.)
              ((3. |$te| 3. 0. 3.) . 0.))
             NIL NIL (((3. |$te| 3. 1. 1.) . 0.)) NIL
             (((3. |$te| 1. 3. 3.) . 0.)) NIL
             (((3. |$te| 2. 3. 0.) . 0.) ((3. |$tm| 3. 3. 2.) . 0.))
             (((3. |$tm| 0. 0. 1.) . 0.)) NIL NIL NIL
             (((3. |$te| 2. 3. 3.) . 0.)) NIL (((3. |$te| 3. 3. 0.) . 0.))
             (((3. |$tm| 1. 0. 1.) . 0.)) (((3. |$tm| 0. 1. 2.) . 0.)) NIL NIL
             (((3. |$te| 3. 3. 3.) . 0.)) (((3. |$te| 0. 0. 2.) . 0.)) NIL
             (((3. |$tm| 2. 0. 1.) . 0.))
             (((3. |$te| 0. 1. 0.) . 0.)
              ((3. |$tm| 1. 1. 2.) (MTIMES SIMP) 8. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -1.)
               ((MEXPT SIMP)
                ((MPLUS SIMP)
                 ((MTIMES SIMP) 8. ((MEXPT SIMP RATSIMP) $A 3.) $B)
                 ((MTIMES SIMP) 8. $A ((MEXPT SIMP RATSIMP) $B 3.)))
                -1.)
               ((MEXPT SIMP) $C -4.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 24. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) 24. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 6.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) 39. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) 51. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 4.))
                    ((MTIMES SIMP) 12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $B 6.)))
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -2. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.))
                    ((MTIMES SIMP) -9. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) -7. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%COS SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.))
                ((MTIMES SIMP)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -30. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 3.))
                  ((MTIMES SIMP) 12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 2.)))
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MEXPT SIMP RATSIMP) $C 3.) $Ε
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 24. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) 24. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 6.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -20. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.))
                    ((MTIMES SIMP) -20. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.)))
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%SIN SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.)))))
             NIL NIL NIL
             (((3. |$tm| 0. 3. 1.) . 0.) ((3. |$te| 1. 0. 2.) . 0.))
             (((3. |$te| 0. 1. 3.) . 0.)) (((3. |$tm| 3. 0. 1.) . 0.))
             (((3. |$te| 1. 1. 0.) . 0.) ((3. |$tm| 2. 1. 2.) . 0.)) NIL NIL
             NIL (((3. |$tm| 1. 3. 1.) . 0.) ((3. |$te| 2. 0. 2.) . 0.))
             (((3. |$te| 1. 1. 3.) . 0.)) NIL
             (((3. |$te| 2. 1. 0.) . 0.) ((3. |$tm| 3. 1. 2.) . 0.)) NIL
             (((3. |$te| 0. 3. 2.) . 0.)) NIL
             (((3. |$tm| 2. 3. 1.) (MTIMES SIMP) 8. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -1.)
               ((MEXPT SIMP)
                ((MPLUS SIMP) ((MTIMES SIMP) 8. ((MEXPT SIMP RATSIMP) $A 2.))
                 ((MTIMES SIMP) 8. ((MEXPT SIMP RATSIMP) $B 2.)))
                -1.)
               ((MEXPT SIMP) $C -2.)
               ((MPLUS SIMP)
                ((MTIMES SIMP) 11. ((MEXPT SIMP RATSIMP) $%PI 2.)
                 ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A $B
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $C $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MPLUS SIMP)
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -8. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) $B)
                    ((MTIMES SIMP) -8. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $B 3.)))
                   $Ε
                   ((MEXPT SIMP)
                    ((%COS SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                      ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                        ((MEXPT SIMP RATSIMP) $B 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.))
                  ((MTIMES SIMP) 3. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) $B $Ε
                   ((MEXPT SIMP)
                    ((%SIN SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                      ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                        ((MEXPT SIMP RATSIMP) $B 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.)))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((3. |$te| 3. 0. 2.) . 0.))
             (((3. |$te| 2. 1. 3.) . 0.)) NIL (((3. |$te| 3. 1. 0.) . 0.)) NIL
             (((3. |$te| 1. 3. 2.) . 0.)) NIL (((3. |$tm| 3. 3. 1.) . 0.))
             (((3. |$tm| 0. 0. 0.) . 0.) ((3. |$te| 3. 1. 3.) . 0.)) NIL NIL
             NIL (((3. |$te| 2. 3. 2.) . 0.)) (((3. |$tm| 0. 0. 3.) . 0.)) NIL
             (((3. |$tm| 1. 0. 0.) . 0.)) (((3. |$tm| 0. 1. 1.) . 0.)) NIL NIL
             (((3. |$te| 3. 3. 2.) . 0.))
             (((3. |$te| 0. 0. 1.) . 0.) ((3. |$tm| 1. 0. 3.) . 0.)) NIL
             (((3. |$tm| 2. 0. 0.) . 0.)) (((3. |$tm| 1. 1. 1.) . 0.)) NIL NIL
             NIL
             (((3. |$tm| 0. 3. 0.) . 0.) ((3. |$te| 1. 0. 1.) . 0.)
              ((3. |$tm| 2. 0. 3.) . 0.))
             (((3. |$te| 0. 1. 2.) . 0.)) (((3. |$tm| 3. 0. 0.) . 0.))
             (((3. |$tm| 2. 1. 1.) (MTIMES SIMP) -8. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -1.)
               ((MEXPT SIMP)
                ((MPLUS SIMP) ((MTIMES SIMP) 8. ((MEXPT SIMP RATSIMP) $A 2.))
                 ((MTIMES SIMP) 8. ((MEXPT SIMP RATSIMP) $B 2.)))
                -1.)
               ((MEXPT SIMP) $C -2.)
               ((MPLUS SIMP)
                ((MTIMES SIMP) -63. ((MEXPT SIMP RATSIMP) $%PI 2.)
                 ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A $B
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $C $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MPLUS SIMP)
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -24. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) $B)
                    ((MTIMES SIMP) -24. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $B 3.)))
                   $Ε
                   ((MEXPT SIMP)
                    ((%COS SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                      ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                        ((MEXPT SIMP RATSIMP) $B 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.))
                  ((MTIMES SIMP) 41. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) $B $Ε
                   ((MEXPT SIMP)
                    ((%SIN SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                      ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                        ((MEXPT SIMP RATSIMP) $B 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.)))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))))
             NIL (((3. |$tm| 0. 3. 3.) . 0.)) NIL
             (((3. |$tm| 1. 3. 0.) (MTIMES SIMP) -4. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -1.)
               ((MEXPT SIMP)
                ((MPLUS SIMP)
                 ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $A 3.) $B)
                 ((MTIMES SIMP) 4. $A ((MEXPT SIMP RATSIMP) $B 3.)))
                -1.)
               ((MEXPT SIMP) $C -4.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.))
                  ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 2.))
                  ((MTIMES SIMP) 10. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $B 4.)))
                 ((MEXPT SIMP RATSIMP) $C 4.) $Ε
                 ((MEXPT SIMP)
                  ((%COS SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                    ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                      ((MEXPT SIMP RATSIMP) $B 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  3.))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.))
                  ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 2.))
                  ((MTIMES SIMP) -14. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $B 4.)))
                 ((MEXPT SIMP RATSIMP) $C 4.) $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%SIN SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                    ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                      ((MEXPT SIMP RATSIMP) $B 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -8. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) -8. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 6.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) 17. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) 21. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 4.))
                    ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $B 6.)))
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) 10. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.))
                    ((MTIMES SIMP) 3. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) -7. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%COS SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.))
                ((MTIMES SIMP)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 3.) ((MEXPT SIMP RATSIMP) $B 2.)
                   $C)
                  ((MTIMES SIMP) 14. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 3.) ((MEXPT SIMP RATSIMP) $C 3.)))
                 $Ε
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 8. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) 8. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 6.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.))
                    ((MTIMES SIMP) -4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.)))
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%SIN SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.))))
              ((3. |$te| 2. 0. 1.) . 0.) ((3. |$tm| 3. 0. 3.) . 0.))
             (((3. |$te| 1. 1. 2.) . 0.)) NIL (((3. |$tm| 3. 1. 1.) . 0.)) NIL
             (((3. |$te| 0. 3. 1.) . 0.) ((3. |$tm| 1. 3. 3.) . 0.)) NIL
             (((3. |$tm| 2. 3. 0.) . 0.) ((3. |$te| 3. 0. 1.) . 0.))
             (((3. |$te| 2. 1. 2.) . 0.)) NIL NIL NIL)) 
(ADD2LNC '|$projERP| $ARRAYS) 
(DEFPARAMETER AAAAA (GENSYM)) 
(REMCOMPARY '|$projHRP|) 
(MREMPROP '|$projHRP| 'ARRAY) 
(MPUTPROP '|$projHRP| AAAAA 'HASHAR) 
(*ARRAY AAAAA 'T 131.) 
(FILLARRAY AAAAA
           '(128. 96. 5.
             (((3. |$te| 1. 3. 1.) . 0.) ((3. |$tm| 2. 3. 3.) . 0.)) NIL
             (((3. |$tm| 3. 3. 0.) . 0.)) (((3. |$te| 3. 1. 2.) . 0.)) NIL NIL
             NIL
             (((3. |$te| 2. 3. 1.) (MTIMES SIMP) 8. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -1.)
               ((MEXPT SIMP)
                ((MPLUS SIMP)
                 ((MTIMES SIMP) 8. ((MEXPT SIMP RATSIMP) $A 3.) $B)
                 ((MTIMES SIMP) 8. $A ((MEXPT SIMP RATSIMP) $B 3.)))
                -1.)
               ((MEXPT SIMP) $C -2.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) 30. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.))
                    ((MTIMES SIMP) 36. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) 6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 2.) $Ε
                   ((MEXPT SIMP)
                    ((%COS SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                      ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                        ((MEXPT SIMP RATSIMP) $B 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -21. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) -18. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 4.))
                    ((MTIMES SIMP)
                     ((MPLUS SIMP)
                      ((MTIMES SIMP) -12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                       ((MEXPT SIMP RATSIMP) $A 4.))
                      ((MTIMES SIMP) ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                       ((MEXPT SIMP RATSIMP) $A 2.)
                       ((MEXPT SIMP RATSIMP) $B 2.))
                      ((MTIMES SIMP) 6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                       ((MEXPT SIMP RATSIMP) $B 4.)))
                     ((MEXPT SIMP RATSIMP) $C 2.)))
                   $Ε
                   ((MEXPT SIMP)
                    ((%SIN SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                      ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                        ((MEXPT SIMP RATSIMP) $B 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.)))
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 42. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 3.))
                  ((MTIMES SIMP) 14. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 2.)))
                 $C
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((3. |$tm| 3. 3. 3.) . 0.))
             (((3. |$tm| 0. 0. 2.) . 0.)) NIL NIL (((3. |$tm| 0. 1. 0.) . 0.))
             NIL NIL (((3. |$te| 3. 3. 1.) . 0.))
             (((3. |$te| 0. 0. 0.) . 0.) ((3. |$tm| 1. 0. 2.) . 0.))
             (((3. |$tm| 0. 1. 3.) . 0.)) NIL (((3. |$tm| 1. 1. 0.) . 0.)) NIL
             (((3. |$te| 0. 0. 3.) . 0.)) NIL
             (((3. |$te| 1. 0. 0.) . 0.) ((3. |$tm| 2. 0. 2.) . 0.))
             (((3. |$te| 0. 1. 1.) (MTIMES SIMP) -4. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -1.)
               ((MEXPT SIMP)
                ((MPLUS SIMP)
                 ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $A 2.) $B)
                 ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $B 3.)))
                -1.)
               ((MEXPT SIMP) $C -4.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -18. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 3.))
                    ((MTIMES SIMP) -18. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                     ((MEXPT SIMP RATSIMP) $B 2.)))
                   ((MEXPT SIMP RATSIMP) $C 4.) $Ε
                   ((MEXPT SIMP)
                    ((%COS SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                      ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                        ((MEXPT SIMP RATSIMP) $B 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP)
                     ((MPLUS SIMP)
                      ((MTIMES SIMP) -7. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                       ((MEXPT SIMP RATSIMP) $A 3.)
                       ((MEXPT SIMP RATSIMP) $B 2.))
                      ((MTIMES SIMP) -12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                       ((MEXPT SIMP RATSIMP) $B 4.)))
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((MTIMES SIMP)
                     ((MPLUS SIMP)
                      ((MTIMES SIMP) -4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                       ((MEXPT SIMP RATSIMP) $A 3.))
                      ((MTIMES SIMP) 11. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                       ((MEXPT SIMP RATSIMP) $B 2.)))
                     ((MEXPT SIMP RATSIMP) $C 4.)))
                   $Ε
                   ((MEXPT SIMP)
                    ((%SIN SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                      ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                        ((MEXPT SIMP RATSIMP) $B 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.)))
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 3.) ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) -6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 6.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 3.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 3.))
                    ((MTIMES SIMP) -6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                     ((MEXPT SIMP RATSIMP) $B 2.)))
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((MEXPT SIMP)
                  ((%COS SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  3.))
                ((MTIMES SIMP)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 2. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.))
                  ((MTIMES SIMP) 24. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $B 2.)))
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MEXPT SIMP RATSIMP) $C 3.) $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -30. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 3.) ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) -30. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 6.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -60. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 3.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) -60. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -30. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 3.))
                    ((MTIMES SIMP) -30. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                     ((MEXPT SIMP RATSIMP) $B 2.)))
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%SIN SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.))))
              ((3. |$tm| 1. 1. 3.) . 0.))
             NIL (((3. |$tm| 2. 1. 0.) . 0.)) NIL
             (((3. |$tm| 0. 3. 2.) . 0.) ((3. |$te| 1. 0. 3.) . 0.)) NIL
             (((3. |$te| 2. 0. 0.) . 0.) ((3. |$tm| 3. 0. 2.) . 0.))
             (((3. |$te| 1. 1. 1.) . 0.) ((3. |$tm| 2. 1. 3.) . 0.)) NIL
             (((3. |$tm| 3. 1. 0.) . 0.)) NIL
             (((3. |$te| 0. 3. 0.) . 0.) ((3. |$tm| 1. 3. 2.) . 0.)
              ((3. |$te| 2. 0. 3.) . 0.))
             NIL (((3. |$te| 3. 0. 0.) . 0.))
             (((3. |$te| 2. 1. 1.) (MTIMES SIMP) -8. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -1.)
               ((MEXPT SIMP)
                ((MPLUS SIMP)
                 ((MTIMES SIMP) 8. ((MEXPT SIMP RATSIMP) $A 3.) $B)
                 ((MTIMES SIMP) 8. $A ((MEXPT SIMP RATSIMP) $B 3.)))
                -1.)
               ((MEXPT SIMP) $C -2.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) 18. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.))
                    ((MTIMES SIMP) 24. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) 6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 2.) $Ε
                   ((MEXPT SIMP)
                    ((%COS SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                      ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                        ((MEXPT SIMP RATSIMP) $B 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) 7. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 4.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) -18. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 4.))
                    ((MTIMES SIMP)
                     ((MPLUS SIMP)
                      ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                       ((MEXPT SIMP RATSIMP) $A 4.))
                      ((MTIMES SIMP) 21. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                       ((MEXPT SIMP RATSIMP) $A 2.)
                       ((MEXPT SIMP RATSIMP) $B 2.))
                      ((MTIMES SIMP) 6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                       ((MEXPT SIMP RATSIMP) $B 4.)))
                     ((MEXPT SIMP RATSIMP) $C 2.)))
                   $Ε
                   ((MEXPT SIMP)
                    ((%SIN SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                      ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                        ((MEXPT SIMP RATSIMP) $B 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.)))
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -2. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 3.))
                  ((MTIMES SIMP) 14. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 2.)))
                 $C
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((3. |$tm| 3. 1. 3.) . 0.))
             NIL
             (((3. |$te| 0. 3. 3.) (MTIMES SIMP) -2. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -2.) ((MEXPT SIMP) $C -4.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 3. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) 6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 2.) ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP) 3. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((MEXPT SIMP)
                  ((%COS SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  3.))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 3. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) 6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 2.) ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP) 3. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%SIN SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.)))))
             NIL
             (((3. |$te| 1. 3. 0.) . 0.) ((3. |$tm| 2. 3. 2.) . 0.)
              ((3. |$te| 3. 0. 3.) . 0.))
             NIL NIL (((3. |$te| 3. 1. 1.) . 0.)) NIL
             (((3. |$te| 1. 3. 3.) . 0.)) NIL
             (((3. |$te| 2. 3. 0.) . 0.) ((3. |$tm| 3. 3. 2.) . 0.))
             (((3. |$tm| 0. 0. 1.) . 0.)) NIL NIL NIL
             (((3. |$te| 2. 3. 3.) . 0.)) NIL (((3. |$te| 3. 3. 0.) . 0.))
             (((3. |$tm| 1. 0. 1.) . 0.)) (((3. |$tm| 0. 1. 2.) . 0.)) NIL NIL
             (((3. |$te| 3. 3. 3.) . 0.)) (((3. |$te| 0. 0. 2.) . 0.)) NIL
             (((3. |$tm| 2. 0. 1.) . 0.))
             (((3. |$te| 0. 1. 0.) . 0.) ((3. |$tm| 1. 1. 2.) . 0.)) NIL NIL
             NIL (((3. |$tm| 0. 3. 1.) . 0.) ((3. |$te| 1. 0. 2.) . 0.))
             (((3. |$te| 0. 1. 3.) (MTIMES SIMP) -2. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -2.) ((MEXPT SIMP) $C -4.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -3. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) 2. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 2.) ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP) ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((MEXPT SIMP)
                  ((%COS SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  3.))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -3. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) 2. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 2.) ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP) 5. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%SIN SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.)))))
             (((3. |$tm| 3. 0. 1.) . 0.))
             (((3. |$te| 1. 1. 0.) . 0.) ((3. |$tm| 2. 1. 2.) . 0.)) NIL NIL
             NIL (((3. |$tm| 1. 3. 1.) . 0.) ((3. |$te| 2. 0. 2.) . 0.))
             (((3. |$te| 1. 1. 3.) . 0.)) NIL
             (((3. |$te| 2. 1. 0.) . 0.) ((3. |$tm| 3. 1. 2.) . 0.)) NIL
             (((3. |$te| 0. 3. 2.) . 0.)) NIL
             (((3. |$tm| 2. 3. 1.) . 0.) ((3. |$te| 3. 0. 2.) . 0.))
             (((3. |$te| 2. 1. 3.) . 0.)) NIL (((3. |$te| 3. 1. 0.) . 0.)) NIL
             (((3. |$te| 1. 3. 2.) (MTIMES SIMP) -8. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -1.)
               ((MEXPT SIMP)
                ((MPLUS SIMP) ((MTIMES SIMP) 8. ((MEXPT SIMP RATSIMP) $A 3.))
                 ((MTIMES SIMP) 8. $A ((MEXPT SIMP RATSIMP) $B 2.)))
                -1.)
               ((MEXPT SIMP) $C -3.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 5. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 3.) $B)
                  ((MTIMES SIMP) 5. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 3.)))
                 $C
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MPLUS SIMP)
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -27. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 3.))
                    ((MTIMES SIMP)
                     ((MPLUS SIMP)
                      ((MTIMES SIMP) -32. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                       ((MEXPT SIMP RATSIMP) $A 2.) $B)
                      ((MTIMES SIMP) 3. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                       ((MEXPT SIMP RATSIMP) $B 3.)))
                     ((MEXPT SIMP RATSIMP) $C 2.)))
                   $Ε
                   ((%SIN SIMP)
                    ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                     ((MEXPT SIMP) $B -1.)
                     ((MEXPT SIMP)
                      ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                       ((MEXPT SIMP RATSIMP) $B 2.))
                      ((RAT SIMP) 1. 2.))
                     $T))
                   ((MEXPT SIMP)
                    ((%COS SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP) $C -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                        ((MEXPT SIMP RATSIMP) $C 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -27. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 3.))
                    ((MTIMES SIMP) -27. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) $B
                     ((MEXPT SIMP RATSIMP) $C 2.)))
                   $Ε
                   ((%SIN SIMP)
                    ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                     ((MEXPT SIMP) $B -1.)
                     ((MEXPT SIMP)
                      ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                       ((MEXPT SIMP RATSIMP) $B 2.))
                      ((RAT SIMP) 1. 2.))
                     $T))
                   ((MEXPT SIMP)
                    ((%SIN SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP) $C -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                        ((MEXPT SIMP RATSIMP) $C 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.)))))))
             NIL (((3. |$tm| 3. 3. 1.) . 0.))
             (((3. |$tm| 0. 0. 0.) . 0.) ((3. |$te| 3. 1. 3.) . 0.)) NIL NIL
             NIL (((3. |$te| 2. 3. 2.) . 0.)) (((3. |$tm| 0. 0. 3.) . 0.)) NIL
             (((3. |$tm| 1. 0. 0.) . 0.)) (((3. |$tm| 0. 1. 1.) . 0.)) NIL NIL
             (((3. |$te| 3. 3. 2.) . 0.))
             (((3. |$te| 0. 0. 1.) . 0.) ((3. |$tm| 1. 0. 3.) . 0.)) NIL
             (((3. |$tm| 2. 0. 0.) . 0.)) (((3. |$tm| 1. 1. 1.) . 0.)) NIL NIL
             NIL
             (((3. |$tm| 0. 3. 0.) . 0.) ((3. |$te| 1. 0. 1.) . 0.)
              ((3. |$tm| 2. 0. 3.) . 0.))
             (((3. |$te| 0. 1. 2.) . 0.)) (((3. |$tm| 3. 0. 0.) . 0.))
             (((3. |$tm| 2. 1. 1.) . 0.)) NIL (((3. |$tm| 0. 3. 3.) . 0.)) NIL
             (((3. |$tm| 1. 3. 0.) . 0.) ((3. |$te| 2. 0. 1.) . 0.)
              ((3. |$tm| 3. 0. 3.) . 0.))
             (((3. |$te| 1. 1. 2.) (MTIMES SIMP) 8. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -1.)
               ((MEXPT SIMP)
                ((MPLUS SIMP) ((MTIMES SIMP) 8. ((MEXPT SIMP RATSIMP) $A 3.))
                 ((MTIMES SIMP) 8. $A ((MEXPT SIMP RATSIMP) $B 2.)))
                -1.)
               ((MEXPT SIMP) $C -3.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 5. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 3.) $B)
                  ((MTIMES SIMP) 5. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 3.)))
                 $C
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MPLUS SIMP)
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -27. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 3.))
                    ((MTIMES SIMP) 3. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $B 3.)
                     ((MEXPT SIMP RATSIMP) $C 2.)))
                   $Ε
                   ((%SIN SIMP)
                    ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                     ((MEXPT SIMP) $B -1.)
                     ((MEXPT SIMP)
                      ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                       ((MEXPT SIMP RATSIMP) $B 2.))
                      ((RAT SIMP) 1. 2.))
                     $T))
                   ((MEXPT SIMP)
                    ((%COS SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP) $C -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                        ((MEXPT SIMP RATSIMP) $C 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -27. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) ((MEXPT SIMP RATSIMP) $B 3.))
                    ((MTIMES SIMP) -27. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 2.) $B
                     ((MEXPT SIMP RATSIMP) $C 2.)))
                   $Ε
                   ((%SIN SIMP)
                    ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                     ((MEXPT SIMP) $B -1.)
                     ((MEXPT SIMP)
                      ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                       ((MEXPT SIMP RATSIMP) $B 2.))
                      ((RAT SIMP) 1. 2.))
                     $T))
                   ((MEXPT SIMP)
                    ((%SIN SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP) $C -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                        ((MEXPT SIMP RATSIMP) $C 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.)))))))
             NIL (((3. |$tm| 3. 1. 1.) . 0.)) NIL
             (((3. |$te| 0. 3. 1.) (MTIMES SIMP) 4. ((MEXPT SIMP) $A -1.)
               ((MEXPT SIMP) $B -1.)
               ((MEXPT SIMP)
                ((MPLUS SIMP)
                 ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $A 2.) $B)
                 ((MTIMES SIMP) 4. ((MEXPT SIMP RATSIMP) $B 3.)))
                -1.)
               ((MEXPT SIMP) $C -4.)
               ((MPLUS SIMP)
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -30. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 3.))
                    ((MTIMES SIMP) -30. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                     ((MEXPT SIMP RATSIMP) $B 2.)))
                   ((MEXPT SIMP RATSIMP) $C 4.) $Ε
                   ((MEXPT SIMP)
                    ((%COS SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                      ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                        ((MEXPT SIMP RATSIMP) $B 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP)
                     ((MPLUS SIMP)
                      ((MTIMES SIMP) 21. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                       ((MEXPT SIMP RATSIMP) $A 3.)
                       ((MEXPT SIMP RATSIMP) $B 2.))
                      ((MTIMES SIMP) -12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                       ((MEXPT SIMP RATSIMP) $B 4.)))
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((MTIMES SIMP)
                     ((MPLUS SIMP)
                      ((MTIMES SIMP) 12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                       ((MEXPT SIMP RATSIMP) $A 3.))
                      ((MTIMES SIMP) -33. ((MEXPT SIMP RATSIMP) $%PI 2.)
                       ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                       ((MEXPT SIMP RATSIMP) $B 2.)))
                     ((MEXPT SIMP RATSIMP) $C 4.)))
                   $Ε
                   ((MEXPT SIMP)
                    ((%SIN SIMP)
                     ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                      ((MEXPT SIMP) $B -1.)
                      ((MEXPT SIMP)
                       ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                        ((MEXPT SIMP RATSIMP) $B 2.))
                       ((RAT SIMP) 1. 2.))
                      $T))
                    2.)))
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 3.) ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) -6. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 6.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 3.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) -12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) 18. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 3.))
                    ((MTIMES SIMP) 18. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                     ((MEXPT SIMP RATSIMP) $B 2.)))
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((MEXPT SIMP)
                  ((%COS SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  3.))
                ((MTIMES SIMP)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -42. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 2.))
                  ((MTIMES SIMP) 24. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $B 2.)))
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 ((MEXPT SIMP RATSIMP) $C 3.) $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.)
                   ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((%SIN SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))
                ((MTIMES SIMP)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -30. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                   ((MEXPT SIMP RATSIMP) $A 3.) ((MEXPT SIMP RATSIMP) $B 4.))
                  ((MTIMES SIMP) -30. ((MEXPT SIMP RATSIMP) $%PI 2.)
                   ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                   ((MEXPT SIMP RATSIMP) $B 6.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) -12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 3.) ((MEXPT SIMP RATSIMP) $B 2.))
                    ((MTIMES SIMP) -12. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                     ((MEXPT SIMP RATSIMP) $B 4.)))
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((MTIMES SIMP)
                   ((MPLUS SIMP)
                    ((MTIMES SIMP) 18. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.)
                     ((MEXPT SIMP RATSIMP) $A 3.))
                    ((MTIMES SIMP) 18. ((MEXPT SIMP RATSIMP) $%PI 2.)
                     ((MEXPT SIMP RATSIMP) |$f_0| 3.) $A
                     ((MEXPT SIMP RATSIMP) $B 2.)))
                   ((MEXPT SIMP RATSIMP) $C 4.)))
                 $Ε
                 ((%COS SIMP)
                  ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                   ((MEXPT SIMP) $C -1.)
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))
                 ((MEXPT SIMP)
                  ((%SIN SIMP)
                   ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.)
                    ((MEXPT SIMP) $C -1.)
                    ((MEXPT SIMP)
                     ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                      ((MEXPT SIMP RATSIMP) $C 2.))
                     ((RAT SIMP) 1. 2.))
                    $T))
                  2.))))
              ((3. |$tm| 1. 3. 3.) . 0.))
             NIL (((3. |$tm| 2. 3. 0.) . 0.) ((3. |$te| 3. 0. 1.) . 0.))
             (((3. |$te| 2. 1. 2.) . 0.)) NIL NIL NIL)) 
(ADD2LNC '|$projHRP| $ARRAYS) 