;;; -*- Mode: LISP; package:maxima; syntax:common-lisp; -*- 
(in-package :maxima)
(DSKSETQ $N '3.) 
(ADD2LNC '$N $VALUES) 
(RESTORE-FACTS '((($KIND) $N $INTEGER) ((MGEQP) $N 0.))) 
(ADD2LNC '$N $PROPS) 
(DSKSETQ $P '3.) 
(ADD2LNC '$P $VALUES) 
(RESTORE-FACTS '((($KIND) $P $INTEGER) ((MGEQP) $P 0.))) 
(ADD2LNC '$P $PROPS) 
(DSKSETQ $Q '3.) 
(ADD2LNC '$Q $VALUES) 
(RESTORE-FACTS '((($KIND) $Q $INTEGER) ((MGEQP) $Q 0.))) 
(ADD2LNC '$Q $PROPS) 
(DEFPARAMETER AAAAA (GENSYM)) 
(REMCOMPARY '|$specERP|) 
(MREMPROP '|$specERP| 'ARRAY) 
(MPUTPROP '|$specERP| AAAAA 'HASHAR) 
(*ARRAY AAAAA 'T 131.) 
(FILLARRAY AAAAA
           '(128. 96. 4. (((|$te| 3. 1. 2.) (MLIST SIMP))) NIL NIL NIL NIL NIL
             NIL NIL NIL NIL NIL (((|$te| 0. 3. 2.) (MLIST SIMP)))
             (((|$te| 1. 3. 2.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -1. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))))
             (((|$te| 2. 3. 2.) (MLIST SIMP)))
             (((|$te| 3. 3. 2.) (MLIST SIMP))) NIL NIL NIL NIL
             (((|$tm| 0. 0. 2.) (MLIST SIMP)))
             (((|$te| 0. 0. 0.) (MLIST SIMP)) ((|$tm| 1. 0. 2.) (MLIST SIMP)))
             (((|$te| 1. 0. 0.) (MLIST SIMP)) ((|$tm| 2. 0. 2.) (MLIST SIMP)))
             (((|$te| 2. 0. 0.) (MLIST SIMP)) ((|$tm| 3. 0. 2.) (MLIST SIMP)))
             (((|$te| 3. 0. 0.) (MLIST SIMP))) NIL NIL
             (((|$tm| 0. 1. 2.) (MLIST SIMP)))
             (((|$te| 0. 1. 0.) (MLIST SIMP))
              ((|$tm| 1. 1. 2.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -1. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))))
             (((|$te| 1. 1. 0.) (MLIST SIMP)) ((|$tm| 2. 1. 2.) (MLIST SIMP)))
             (((|$te| 2. 1. 0.) (MLIST SIMP)) ((|$tm| 3. 1. 2.) (MLIST SIMP)))
             (((|$te| 3. 1. 0.) (MLIST SIMP))) NIL NIL NIL NIL NIL NIL NIL NIL
             (((|$te| 0. 0. 3.) (MLIST SIMP)))
             (((|$tm| 0. 3. 2.) (MLIST SIMP)) ((|$te| 1. 0. 3.) (MLIST SIMP)))
             (((|$te| 0. 3. 0.) (MLIST SIMP))
              ((|$tm| 1. 3. 2.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -1. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$te| 2. 0. 3.) (MLIST SIMP)))
             (((|$te| 1. 3. 0.) (MLIST SIMP)) ((|$tm| 2. 3. 2.) (MLIST SIMP))
              ((|$te| 3. 0. 3.) (MLIST SIMP)))
             (((|$te| 2. 3. 0.) (MLIST SIMP)) ((|$tm| 3. 3. 2.) (MLIST SIMP)))
             (((|$te| 3. 3. 0.) (MLIST SIMP))) NIL
             (((|$te| 0. 1. 3.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) 3. $%PI ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))))
             (((|$te| 1. 1. 3.) (MLIST SIMP)))
             (((|$te| 2. 1. 3.) (MLIST SIMP)))
             (((|$tm| 0. 0. 0.) (MLIST SIMP)) ((|$te| 3. 1. 3.) (MLIST SIMP)))
             (((|$tm| 1. 0. 0.) (MLIST SIMP)))
             (((|$tm| 2. 0. 0.) (MLIST SIMP)))
             (((|$tm| 3. 0. 0.) (MLIST SIMP))) NIL NIL NIL
             (((|$tm| 0. 1. 0.) (MLIST SIMP)))
             (((|$tm| 1. 1. 0.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) 3. $%PI ((MEXPT SIMP) $A -1.)
                 ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -1. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))))
             (((|$tm| 2. 1. 0.) (MLIST SIMP)))
             (((|$tm| 3. 1. 0.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) 3. $%PI ((MEXPT SIMP) $A -1.)
                 ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))))
             (((|$te| 0. 3. 3.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))))
             (((|$te| 1. 3. 3.) (MLIST SIMP)))
             (((|$te| 2. 3. 3.) (MLIST SIMP)))
             (((|$te| 3. 3. 3.) (MLIST SIMP))) NIL NIL NIL NIL
             (((|$tm| 0. 0. 3.) (MLIST SIMP)))
             (((|$te| 0. 0. 1.) (MLIST SIMP)) ((|$tm| 1. 0. 3.) (MLIST SIMP)))
             (((|$tm| 0. 3. 0.) (MLIST SIMP)) ((|$te| 1. 0. 1.) (MLIST SIMP))
              ((|$tm| 2. 0. 3.) (MLIST SIMP)))
             (((|$tm| 1. 3. 0.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) 3. $%PI ((MEXPT SIMP) $A -1.)
                 ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -1. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$te| 2. 0. 1.) (MLIST SIMP)) ((|$tm| 3. 0. 3.) (MLIST SIMP)))
             (((|$tm| 2. 3. 0.) (MLIST SIMP)) ((|$te| 3. 0. 1.) (MLIST SIMP)))
             (((|$tm| 3. 3. 0.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))))
             NIL (((|$tm| 0. 1. 3.) (MLIST SIMP)))
             (((|$te| 0. 1. 1.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) 3. $%PI ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$tm| 1. 1. 3.) (MLIST SIMP)))
             (((|$te| 1. 1. 1.) (MLIST SIMP)) ((|$tm| 2. 1. 3.) (MLIST SIMP)))
             (((|$te| 2. 1. 1.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$tm| 3. 1. 3.) (MLIST SIMP)))
             (((|$te| 3. 1. 1.) (MLIST SIMP))) NIL NIL NIL NIL NIL NIL NIL NIL
             NIL (((|$tm| 0. 3. 3.) (MLIST SIMP)))
             (((|$te| 0. 3. 1.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) 3. $%PI ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$tm| 1. 3. 3.) (MLIST SIMP)))
             (((|$te| 1. 3. 1.) (MLIST SIMP)) ((|$tm| 2. 3. 3.) (MLIST SIMP)))
             (((|$te| 2. 3. 1.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$tm| 3. 3. 3.) (MLIST SIMP)))
             (((|$te| 3. 3. 1.) (MLIST SIMP))) NIL NIL NIL NIL
             (((|$tm| 0. 0. 1.) (MLIST SIMP)))
             (((|$tm| 1. 0. 1.) (MLIST SIMP)))
             (((|$tm| 2. 0. 1.) (MLIST SIMP)))
             (((|$tm| 3. 0. 1.) (MLIST SIMP))) NIL NIL NIL
             (((|$tm| 0. 1. 1.) (MLIST SIMP)))
             (((|$tm| 1. 1. 1.) (MLIST SIMP)))
             (((|$tm| 2. 1. 1.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))))
             (((|$tm| 3. 1. 1.) (MLIST SIMP))) NIL NIL NIL NIL NIL NIL NIL NIL
             NIL (((|$te| 0. 0. 2.) (MLIST SIMP)))
             (((|$tm| 0. 3. 1.) (MLIST SIMP)) ((|$te| 1. 0. 2.) (MLIST SIMP)))
             (((|$tm| 1. 3. 1.) (MLIST SIMP)) ((|$te| 2. 0. 2.) (MLIST SIMP)))
             (((|$tm| 2. 3. 1.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$te| 3. 0. 2.) (MLIST SIMP)))
             (((|$tm| 3. 3. 1.) (MLIST SIMP))) NIL NIL
             (((|$te| 0. 1. 2.) (MLIST SIMP)))
             (((|$te| 1. 1. 2.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -1. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))))
             (((|$te| 2. 1. 2.) (MLIST SIMP))))) 
(ADD2LNC '|$specERP| $ARRAYS) 
(DEFPARAMETER AAAAA (GENSYM)) 
(REMCOMPARY '|$specHRP|) 
(MREMPROP '|$specHRP| 'ARRAY) 
(MPUTPROP '|$specHRP| AAAAA 'HASHAR) 
(*ARRAY AAAAA 'T 131.) 
(FILLARRAY AAAAA
           '(128. 96. 4. (((|$te| 3. 1. 2.) (MLIST SIMP))) NIL NIL NIL NIL NIL
             NIL NIL NIL NIL NIL (((|$te| 0. 3. 2.) (MLIST SIMP)))
             (((|$te| 1. 3. 2.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -1. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))))
             (((|$te| 2. 3. 2.) (MLIST SIMP)))
             (((|$te| 3. 3. 2.) (MLIST SIMP))) NIL NIL NIL NIL
             (((|$tm| 0. 0. 2.) (MLIST SIMP)))
             (((|$te| 0. 0. 0.) (MLIST SIMP)) ((|$tm| 1. 0. 2.) (MLIST SIMP)))
             (((|$te| 1. 0. 0.) (MLIST SIMP)) ((|$tm| 2. 0. 2.) (MLIST SIMP)))
             (((|$te| 2. 0. 0.) (MLIST SIMP)) ((|$tm| 3. 0. 2.) (MLIST SIMP)))
             (((|$te| 3. 0. 0.) (MLIST SIMP))) NIL NIL
             (((|$tm| 0. 1. 2.) (MLIST SIMP)))
             (((|$te| 0. 1. 0.) (MLIST SIMP))
              ((|$tm| 1. 1. 2.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -1. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))))
             (((|$te| 1. 1. 0.) (MLIST SIMP)) ((|$tm| 2. 1. 2.) (MLIST SIMP)))
             (((|$te| 2. 1. 0.) (MLIST SIMP)) ((|$tm| 3. 1. 2.) (MLIST SIMP)))
             (((|$te| 3. 1. 0.) (MLIST SIMP))) NIL NIL NIL NIL NIL NIL NIL NIL
             (((|$te| 0. 0. 3.) (MLIST SIMP)))
             (((|$tm| 0. 3. 2.) (MLIST SIMP)) ((|$te| 1. 0. 3.) (MLIST SIMP)))
             (((|$te| 0. 3. 0.) (MLIST SIMP))
              ((|$tm| 1. 3. 2.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -1. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$te| 2. 0. 3.) (MLIST SIMP)))
             (((|$te| 1. 3. 0.) (MLIST SIMP)) ((|$tm| 2. 3. 2.) (MLIST SIMP))
              ((|$te| 3. 0. 3.) (MLIST SIMP)))
             (((|$te| 2. 3. 0.) (MLIST SIMP)) ((|$tm| 3. 3. 2.) (MLIST SIMP)))
             (((|$te| 3. 3. 0.) (MLIST SIMP))) NIL
             (((|$te| 0. 1. 3.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) 3. $%PI ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))))
             (((|$te| 1. 1. 3.) (MLIST SIMP)))
             (((|$te| 2. 1. 3.) (MLIST SIMP)))
             (((|$tm| 0. 0. 0.) (MLIST SIMP)) ((|$te| 3. 1. 3.) (MLIST SIMP)))
             (((|$tm| 1. 0. 0.) (MLIST SIMP)))
             (((|$tm| 2. 0. 0.) (MLIST SIMP)))
             (((|$tm| 3. 0. 0.) (MLIST SIMP))) NIL NIL NIL
             (((|$tm| 0. 1. 0.) (MLIST SIMP)))
             (((|$tm| 1. 1. 0.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) 3. $%PI ((MEXPT SIMP) $A -1.)
                 ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -1. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))))
             (((|$tm| 2. 1. 0.) (MLIST SIMP)))
             (((|$tm| 3. 1. 0.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) 3. $%PI ((MEXPT SIMP) $A -1.)
                 ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))))
             (((|$te| 0. 3. 3.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))))
             (((|$te| 1. 3. 3.) (MLIST SIMP)))
             (((|$te| 2. 3. 3.) (MLIST SIMP)))
             (((|$te| 3. 3. 3.) (MLIST SIMP))) NIL NIL NIL NIL
             (((|$tm| 0. 0. 3.) (MLIST SIMP)))
             (((|$te| 0. 0. 1.) (MLIST SIMP)) ((|$tm| 1. 0. 3.) (MLIST SIMP)))
             (((|$tm| 0. 3. 0.) (MLIST SIMP)) ((|$te| 1. 0. 1.) (MLIST SIMP))
              ((|$tm| 2. 0. 3.) (MLIST SIMP)))
             (((|$tm| 1. 3. 0.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) 3. $%PI ((MEXPT SIMP) $A -1.)
                 ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -1. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$te| 2. 0. 1.) (MLIST SIMP)) ((|$tm| 3. 0. 3.) (MLIST SIMP)))
             (((|$tm| 2. 3. 0.) (MLIST SIMP)) ((|$te| 3. 0. 1.) (MLIST SIMP)))
             (((|$tm| 3. 3. 0.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))))
             NIL (((|$tm| 0. 1. 3.) (MLIST SIMP)))
             (((|$te| 0. 1. 1.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) 3. $%PI ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$tm| 1. 1. 3.) (MLIST SIMP)))
             (((|$te| 1. 1. 1.) (MLIST SIMP)) ((|$tm| 2. 1. 3.) (MLIST SIMP)))
             (((|$te| 2. 1. 1.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$tm| 3. 1. 3.) (MLIST SIMP)))
             (((|$te| 3. 1. 1.) (MLIST SIMP))) NIL NIL NIL NIL NIL NIL NIL NIL
             NIL (((|$tm| 0. 3. 3.) (MLIST SIMP)))
             (((|$te| 0. 3. 1.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) 3. $%PI ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$tm| 1. 3. 3.) (MLIST SIMP)))
             (((|$te| 1. 3. 1.) (MLIST SIMP)) ((|$tm| 2. 3. 3.) (MLIST SIMP)))
             (((|$te| 2. 3. 1.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$tm| 3. 3. 3.) (MLIST SIMP)))
             (((|$te| 3. 3. 1.) (MLIST SIMP))) NIL NIL NIL NIL
             (((|$tm| 0. 0. 1.) (MLIST SIMP)))
             (((|$tm| 1. 0. 1.) (MLIST SIMP)))
             (((|$tm| 2. 0. 1.) (MLIST SIMP)))
             (((|$tm| 3. 0. 1.) (MLIST SIMP))) NIL NIL NIL
             (((|$tm| 0. 1. 1.) (MLIST SIMP)))
             (((|$tm| 1. 1. 1.) (MLIST SIMP)))
             (((|$tm| 2. 1. 1.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))))
             (((|$tm| 3. 1. 1.) (MLIST SIMP))) NIL NIL NIL NIL NIL NIL NIL NIL
             NIL (((|$te| 0. 0. 2.) (MLIST SIMP)))
             (((|$tm| 0. 3. 1.) (MLIST SIMP)) ((|$te| 1. 0. 2.) (MLIST SIMP)))
             (((|$tm| 1. 3. 1.) (MLIST SIMP)) ((|$te| 2. 0. 2.) (MLIST SIMP)))
             (((|$tm| 2. 3. 1.) (MLIST SIMP)
               ((%COS SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $B -1.) ((MEXPT SIMP) $C -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                   ((MEXPT SIMP RATSIMP) $C 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%COS SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) 2. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T)))))
              ((|$te| 3. 0. 2.) (MLIST SIMP)))
             (((|$tm| 3. 3. 1.) (MLIST SIMP))) NIL NIL
             (((|$te| 0. 1. 2.) (MLIST SIMP)))
             (((|$te| 1. 1. 2.) (MLIST SIMP)
               ((%SIN SIMP)
                ((MTIMES SIMP) $%PI ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP)
                  ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                   ((MEXPT SIMP RATSIMP) $B 2.))
                  ((RAT SIMP) 1. 2.))
                 $T))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) -1. $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))
               ((%SIN SIMP)
                ((MTIMES SIMP) ((MEXPT SIMP) $A -1.) ((MEXPT SIMP) $B -1.)
                 ((MEXPT SIMP) $C -1.)
                 ((MPLUS SIMP)
                  ((MTIMES SIMP) $%PI
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $A 2.)
                     ((MEXPT SIMP RATSIMP) $B 2.))
                    ((RAT SIMP) 1. 2.))
                   $C $T)
                  ((MTIMES SIMP) 2. $%PI $A
                   ((MEXPT SIMP)
                    ((MPLUS SIMP) ((MEXPT SIMP RATSIMP) $B 2.)
                     ((MEXPT SIMP RATSIMP) $C 2.))
                    ((RAT SIMP) 1. 2.))
                   $T))))))
             (((|$te| 2. 1. 2.) (MLIST SIMP))))) 
(ADD2LNC '|$specHRP| $ARRAYS) 